export const Data = [
    { id: 1, name: 'Apple Inc.', symbol: 'AAPL' },
    { id: 2, name: 'Tesla Inc.', symbol: 'TSLA' },
    { id: 3, name: 'Bitcoin', symbol: 'BTC' },
    { id: 4, name: 'Ethereum', symbol: 'ETH' },
    { id: 5, name: 'Google LLC', symbol: 'GOOGL' },
    { id: 6, name: 'Microsoft Corporation', symbol: 'MSFT' },
    { id: 7, name: 'Amazon.com, Inc.', symbol: 'AMZN' },
    { id: 8, name: 'Meta Platforms Inc.', symbol: 'META' },
    { id: 9, name: 'NVIDIA Corporation', symbol: 'NVDA' },
    { id: 10, name: 'Netflix Inc.', symbol: 'NFLX' },
    { id: 11, name: 'Cardano', symbol: 'ADA' },
    { id: 12, name: 'Ripple', symbol: 'XRP' },
    { id: 13, name: 'Polkadot', symbol: 'DOT' },
    { id: 14, name: 'Solana', symbol: 'SOL' },
    { id: 15, name: 'Dogecoin', symbol: 'DOGE' },
    { id: 16, name: 'Litecoin', symbol: 'LTC' },
    { id: 17, name: 'Chainlink', symbol: 'LINK' },
    { id: 18, name: 'Uniswap', symbol: 'UNI' },
    { id: 19, name: 'Monero', symbol: 'XMR' },
    { id: 20, name: 'Stellar', symbol: 'XLM' },
    { id: 21, name: 'Tether', symbol: 'USDT' },
    { id: 22, name: 'Shiba Inu', symbol: 'SHIB' },
    { id: 23, name: 'Terra', symbol: 'LUNA' },
    { id: 24, name: 'VeChain', symbol: 'VET' },
    { id: 25, name: 'Polygon', symbol: 'MATIC' },
    { id: 26, name: 'Algorand', symbol: 'ALGO' },
    { id: 27, name: 'Aave', symbol: 'AAVE' },
    { id: 28, name: 'SushiSwap', symbol: 'SUSHI' },
    { id: 29, name: 'Cosmos', symbol: 'ATOM' },
    { id: 30, name: 'Maker', symbol: 'MKR' }
  ];